### ISSUE TITLE
Not refreshed home_screen after Editing at form_add_screen .

### ISSUE THREAD

**Issue by david600320** [CoderJava/Flutter-CRUD-API-Sample#2]
Hi,  thanks for sharing nice example to understand Flutter CRUD  for beginners .
In your Demo screens of BLOG  ,  It is well-Refreshing  after Update data and Summit ( for adding New Data ). 

BTW ,  Using downloaded codes , not refreshed after Updating and Inserting Data .

Could you let me know what i am missing ? 

<Env>
- flutter lastest , Android studio

**Comment by CoderJava** [comment]
Hi, thank you for this issue. I have updated the code. 
You can check my commit and it's working.
https://github.com/CoderJava/Flutter-CRUD-API-Sample/commit/c63094f52d9a06ade59ca32d2374b7f620b0ae18
